# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "José Ricardo da Silva"
title-font-size: '4em' # a provision to adjust the size of your title. If it is too long then do resize to a smaller value. By default it will be 4em.

email: root@josericardo.eti.br
description: > # this means to ignore newlines until "baseurl:"
  José Ricardo
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://josericardo.github.io" # the base hostname & protocol for your site
theme: jekyll-theme-architect

permalink: :title/

# Build settings
markdown: kramdown

paginate: 5
paginate_path: /page:num/


# Tracker
#analytics: UA-83979019-1

# Comments
#disqus-shortname: webjeda-demo

# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token:   

#CSS
sass:
  style: compressed


include: [_pages]

gems: [jekyll-paginate, jekyll-seo-tag]
